name: riverpod_swiss_knife
description: A collection of utilities and extensions for Riverpod.
version: 0.0.4
repository: https://github.com/lucavenir/riverpod_swiss_knife

environment:
  sdk: ^3.10.0

dependencies:
  clock: ^1.1.2
  meta: ^1.17.0
  riverpod: ^3.0.3
  time: ^2.1.5

dev_dependencies:
  fake_async: ^1.3.3
  test: ^1.25.6
  very_good_analysis: ^10.0.0
