name: swiss_knife_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  riverpod: ^3.0.3
  time: ^2.1.5
  riverpod_swiss_knife: ^0.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
